name: Check Commit
run-name: Check commit (${{ github.actor }})
on: [push]
jobs:
    lint:
        name: Lint Affected
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - uses: c-hive/gha-npm-cache@v1
            - name: Install JS dependencies
              run: npm ci --ignore-scripts
            - name: Lint affected libs
              run: npm run lint:affected

