name: Check Commit
run-name: Check commit (${{ github.actor }})
on: [push]
jobs:
    prepare:
        steps:
            - uses: actions/checkout@v1
            - uses: c-hive/gha-npm-cache@v1
            - name: Install JS dependencies
              run: npm ci --ignore-scripts
            - name: Lint affected libs
              run: npm run lint:affected
    check:
        name: Check Affected
        runs-on: ubuntu-latest
        needs: [prepare]
        if: ${{ success() }}
        steps:
            - name: Lint affected
              run: npm run lint:affected
            - name: Lint affected
              run: npm run lint:affected
    build:
        name: Build Affected
        runs-on: ubuntu-latest
        needs: [prepare, check]
        if: ${{ success() }}
        steps:
            - run: npm run build:all



