name: Publish To NPM
run-name: Publish ${{  github.ref_name }} tag
on:
    push:
        tags:
            - '[0-9]+.[0-9]+.[0-9]+'
jobs:
    build-and-publish:
        name: Build and Publish
        runs-on: ubuntu-latest

        steps:
            - name: Git checkout
              uses: actions/checkout@v2
              with:
                  persist-credentials: false
                  fetch-depth: 0

            - name: Use Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 16.13.0

            - name: Cache node_modules
              uses: actions/cache@v2
              id: modules-cache
              with:
                  path: '**/node_modules'
                  key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: ${{ runner.os }}-modules-

            - name: Install dependencies
              if: steps.modules-cache.outputs.cache-hit != 'true'
              run: npm ci --ignore-scripts

            - name: Lint affected libs
              run: npm run lint:all

            - name: Test affected libs
              run: npm run test:all

            - name: Build affected libs
              run: npm run build:all

            - name: NPM publish
              env:
                  MOSAIC_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  MOSAIC_REPO_OWNER: mosaic-design
                  MOSAIC_REPO_NAME: infra
              run: |
                  rm -rf .npmrc && echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
                  npm run release:publish-libs -- --without-notification

